[package]
name = "carbon"
version = "0.1.0"
authors = ["AJ <aj@thecampustap.com>"]

[dependencies]
rocksdb = "0.7.1"
ssh2 = "0.3"
serde_derive = "1.0.11"
serde = "1.0.11"
serde_json = "1.0.2"
shrust = "0.0.4"
git2 = "0.6.8"